import { Injectable } from '@angular/core';
    
@Injectable()
export class LeadsService {
    getProductsData() {
        return [
            {
                id: '999',
                nationality: 'Egypt',
                name: 'Black Watch',
                emp: 'Nicola',
                score: 1,
                remindes: "25+ days",
                status:"Docs uploaded",
                phone_number: "0100",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 3
            },
            {
                id: '1000',
                nationality: 'Egypt',
                name: 'Bamboo Watch',
                emp: 'Nicola',
                score: 2,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 10

            },
            {
                id: '1001',
                nationality: 'Egypt',
                name: 'Black Watch',
                emp: 'Nicola',
                score: 3,
                remindes: "25+ days",
                status:"Invited lead",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 15
            },
            {
                id: '1002',
                nationality: 'Egypt',
                name: 'Blue Band',
                emp: 'Nicola',
                score: 4,
                remindes: "25+ days",
                status:"Docs uploaded",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 30
            },
            {
                id: '1003',
                nationality: 'Egypt',
                name: 'Blue T-Shirt',
                emp: 'Nicola',
                score: 5,
                remindes: "25+ days",
                status:"Invited lead",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 5
            },
            {
                id: '1004',
                nationality: 'Egypt',
                name: 'Bracelet',
                emp: 'Nicola',
                score: 2,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 8
            },
            {
                id: '1005',
                nationality: 'Egypt',
                name: 'Brown Purse',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Docs uploaded",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 24
            },
            {
                id: '1006',
                nationality: 'Egypt',
                name: 'Chakra Bracelet',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Docs uploaded",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 15
            },
            {
                id: '1007',
                nationality: 'Egypt',
                name: 'Galaxy Earrings',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 12
            },
            {
                id: '1008',
                nationality: 'Egypt',
                name: 'Game Controller',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 20
            },
            {
                id: '1009',
                nationality: 'Egypt',
                name: 'Gaming Set',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 18
            },
            {
                id: '1010',
                nationality: 'Egypt',
                name: 'Gold Phone Case',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 17
            },
            {
                id: '1011',
                nationality: 'Egypt',
                name: 'Green Earbuds',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 10
            },
            {
                id: '1012',
                nationality: 'Egypt',
                name: 'Green T-Shirt',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
                reminder: 16
            },
            {
                id: '1013',
                nationality: 'Egypt',
                name: 'Grey T-Shirt',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1014',
                nationality: 'Egypt',
                name: 'Headphones',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1015',
                nationality: 'Egypt',
                name: 'Light Green T-Shirt',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1016',
                nationality: 'Egypt',
                name: 'Lime Band',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1017',
                nationality: 'Egypt',
                name: 'Mini Speakers',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1018',
                nationality: 'Egypt',
                name: 'Painted Phone Case',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1019',
                nationality: 'Egypt',
                name: 'Pink Band',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1020',
                nationality: 'Egypt',
                name: 'Pink Purse',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1021',
                nationality: 'Egypt',
                name: 'Purple Band',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1022',
                nationality: 'Egypt',
                name: 'Purple Gemstone Necklace',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1023',
                nationality: 'Egypt',
                name: 'Purple T-Shirt',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1024',
                nationality: 'Egypt',
                name: 'Shoes',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1025',
                nationality: 'Egypt',
                name: 'Sneakers',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1026',
                nationality: 'Egypt',
                name: 'Teal T-Shirt',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1027',
                nationality: 'Egypt',
                name: 'Yellow Earbuds',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1028',
                nationality: 'Egypt',
                name: 'Yoga Mat',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            },
            {
                id: '1029',
                nationality: 'Egypt',
                name: 'Yoga Set',
                emp: 'Nicola',
                score: 7,
                remindes: "25+ days",
                status:"Account Created",
                phone_number: "+33366664454",
                email_address:"awuavictoria2003@gmail.com",
                tags:['Data Science', 'Computer Science', 'Informatique', 'Cybersecurity'],
                source: ['Facebook Groups', 'Study in France FB Group'],
            }
        ];
    }
    getProductsMini() {
        return Promise.resolve(this.getProductsData());
    }

    getProductsSmall() {
        return Promise.resolve(this.getProductsData().slice(0, 10));
    }
};